### PR TITLE
Giant Patch

### PR DESCRIPTION
**Pull request by Soneji**
Hi,

I was trying to use your editor but I found the repository very confusing, especially to do with the large amounts of files in the "text_editor" folder. Please find below a non-exhaustive list of updates I have made to make the project easier to use. 
 - I have updated your repo with a new Makefile and make system for a much more standardised file structure
 - I have created a new file structure with:
   - Headers in the include folder
   - Source code in the src folder
   - Objects in the obj folder
 - I have created a .gitignore file to prevent accidental commits of binary files (e.g. editor), and prevents commits of the objects folder. 
 - I have created a new make option called `make test` which can automatically run all your tests for you. 
 - I have moved vimm.png from the root of the project folder to the assets folder
 - I have updated your README.md:
   - The image src tag is no longer a web link but a local link
   - I have added compilation instructions
   - I have added a list of keyboard shortcuts to document how to use the editor

Overall the purpose of this patch was to make the project easier to use, easier to contribute to, and prevent accidental commits of binary files. Please see the commit history below for more details on the edits I have made. I hope you accept my patch. 

Kind regards
Dhaval

### CODE REVIEW

**Comment by Soneji** [comment]
Thanks @jameshball for the `.gitignore` update
Do you want to merge the PR or add anything else?

**Comment by jameshball** [comment]
@overclockedllama I currently can't get it to compile on my machine - will look at it at some point but feel free to also.

**Comment by Soneji** [comment]
What is the error you are getting?
Have you run `make clean` first?

**Comment by jameshball** [comment]
Getting issues still. Works on master branch but not yours. This is my make output - maybe something to do with ncurses?
```
mkdir -p obj
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/auto_complete.c -o obj/auto_complete.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/editor.c -o obj/editor.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/queue.c -o obj/queue.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/common.c -o obj/common.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/trie.c -o obj/trie.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/parser.c -o obj/parser.o
gcc -Wall -g -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic -c src/vector.c -o obj/vector.o
make: Circular editor <- editor dependency dropped.
gcc -lncurses obj/auto_complete.o obj/editor.o obj/queue.o obj/common.o obj/trie.o obj/parser.o obj/vector.o -o editor
obj/editor.o: In function `move_pos':
/mnt/c/dev/vimm/src/editor.c:23: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:23: undefined reference to `wmove'
obj/editor.o: In function `cursor_pos':
/mnt/c/dev/vimm/src/editor.c:28: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:28: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:28: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:28: undefined reference to `stdscr'
obj/editor.o: In function `render':
/mnt/c/dev/vimm/src/editor.c:56: undefined reference to `stdscr'
obj/editor.o:/mnt/c/dev/vimm/src/editor.c:56: more undefined references to `stdscr' follow
obj/editor.o: In function `render':
/mnt/c/dev/vimm/src/editor.c:58: undefined reference to `wclear'
/mnt/c/dev/vimm/src/editor.c:66: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:66: undefined reference to `waddnstr'
/mnt/c/dev/vimm/src/editor.c:69: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:69: undefined reference to `wmove'
/mnt/c/dev/vimm/src/editor.c:73: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:73: undefined reference to `waddch'
obj/editor.o: In function `move_cursor':
/mnt/c/dev/vimm/src/editor.c:109: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:109: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:109: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:109: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:159: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:159: undefined reference to `wmove'
obj/editor.o: In function `insert_prompt':
/mnt/c/dev/vimm/src/editor.c:192: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:192: undefined reference to `waddch'
obj/editor.o: In function `generate_prompt':
/mnt/c/dev/vimm/src/editor.c:202: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:202: undefined reference to `wattr_on'
/mnt/c/dev/vimm/src/editor.c:203: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:203: undefined reference to `waddnstr'
/mnt/c/dev/vimm/src/editor.c:204: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:204: undefined reference to `wattr_off'
obj/editor.o: In function `clear_prompt':
/mnt/c/dev/vimm/src/editor.c:219: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:219: undefined reference to `waddch'
obj/editor.o: In function `insert_char':
/mnt/c/dev/vimm/src/editor.c:243: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:243: undefined reference to `wmove'
/mnt/c/dev/vimm/src/editor.c:251: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:251: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:251: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:251: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:262: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:262: undefined reference to `waddnstr'
obj/editor.o: In function `backspace':
/mnt/c/dev/vimm/src/editor.c:274: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:274: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:274: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:274: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:285: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:285: undefined reference to `wmove'
/mnt/c/dev/vimm/src/editor.c:290: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:290: undefined reference to `wdelch'
/mnt/c/dev/vimm/src/editor.c:298: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:298: undefined reference to `wmove'
obj/editor.o: In function `cleanup':
/mnt/c/dev/vimm/src/editor.c:334: undefined reference to `endwin'
obj/editor.o: In function `main':
/mnt/c/dev/vimm/src/editor.c:342: undefined reference to `initscr'
/mnt/c/dev/vimm/src/editor.c:343: undefined reference to `start_color'
/mnt/c/dev/vimm/src/editor.c:344: undefined reference to `raw'
/mnt/c/dev/vimm/src/editor.c:345: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:345: undefined reference to `wclear'
/mnt/c/dev/vimm/src/editor.c:346: undefined reference to `noecho'
/mnt/c/dev/vimm/src/editor.c:347: undefined reference to `cbreak'
/mnt/c/dev/vimm/src/editor.c:348: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:348: undefined reference to `keypad'
/mnt/c/dev/vimm/src/editor.c:350: undefined reference to `init_pair'
/mnt/c/dev/vimm/src/editor.c:365: undefined reference to `stdscr'
/mnt/c/dev/vimm/src/editor.c:365: undefined reference to `wgetch'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'editor' failed
make: *** [editor] Error 1
```

**Comment by cbeuw** [comment]
In Makefile $(LDFLAGS) needs to come AFTER the output object file name

**Comment by Soneji** [comment]
That's strange what version of make are you guys using? I'm on:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
and it seems to not matter where I put the LDFLAGS

**Comment by jameshball** [comment]
It now works for me with the updated makefile. 
```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jameshball** [comment]
Thank you Andy ahahahaa

**Comment by Soneji** [comment]
Fantastic! 
What version of gcc are you guys using - I think it might be a gcc issue of where the opts go

**Comment by jameshball** [comment]
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jameshball** [comment]
Thanks for these changes!

**Comment by Soneji** [comment]
no worries :)
```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Maybe it's a darwin vs linux kinda thing 🤷 - Working now though so calm

**Pull request merged**
